// Renders the app icons from the design fonts. Run from the repo root: CHROMIUM=/path/to/chrome node scripts/make-icons.mjs
import fs from "node:fs";
import { chromium } from "playwright-core";

const font = "data:font/woff2;base64," + fs.readFileSync("./node_modules/@fontsource/zcool-qingke-huangyou/files/zcool-qingke-huangyou-latin-400-normal.woff2").toString("base64");
const ms = "data:font/woff2;base64," + fs.readFileSync("./node_modules/material-symbols/material-symbols-rounded.woff2").toString("base64");
const out = "./apps/public/icons/";
const icons = {
  my: { bg: "#0a0a0c", fg: "#f4f3ef", inner: '<div class="w">n</div><div class="dot"></div>' },
  parent: { bg: "#f4f3ef", fg: "#111114", inner: '<div class="w">n</div><div class="dot"></div>' },
  notes: { bg: "#f4f3ef", fg: "#17171b", inner: '<div class="tab"></div><div class="folder"></div><div class="dot" style="left:auto;right:30%;top:58%"></div>' },
  admin: { bg: "#0a0a0c", fg: "#f4f3ef", inner: '<div class="ms">tune</div><div class="dot"></div>' },
  desktop: { bg: "#eae8e1", fg: "#0a0a0c", inner: '<div class="scr"><div class="w" style="color:#f4f3ef;font-size:50%">n</div></div><div class="dot" style="left:74%;top:70%"></div>' },
};
const b = await chromium.launch({ executablePath: process.env.CHROMIUM || "/usr/bin/chromium" });
for (const [id, ic] of Object.entries(icons)) {
  for (const size of [192, 512, 256]) {
    const p = await b.newPage({ viewport: { width: size, height: size } });
    await p.setContent(`<style>@font-face{font-family:Z;src:url(${font})}@font-face{font-family:M;src:url(${ms})}
    html,body{margin:0;width:100%;height:100%;background:${ic.bg};overflow:hidden;font-size:${size}px}
    .w{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-family:Z;font-size:62%;line-height:1;color:${ic.fg};padding-bottom:8%}
    .ms{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-family:M;font-size:46%;color:${ic.fg}}
    .dot{position:absolute;left:62%;top:60%;width:13%;height:13%;border-radius:50%;background:#ff4d17}
    .tab{position:absolute;left:22%;top:30%;width:30%;height:14%;border-radius:8% 8% 0 0;background:${ic.fg}}
    .folder{position:absolute;left:22%;top:40%;width:56%;height:34%;border-radius:0 6% 6% 6%;background:${ic.fg}}
    .scr{position:absolute;left:16%;top:18%;width:52%;height:40%;border-radius:8%;background:#0a0a0c}
    </style>${ic.inner}`);
    await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(200);
    const name = size === 256 ? `${id}.png` : `${id}-${size}.png`;
    await p.screenshot({ path: out + name });
    await p.close();
  }
}
await b.close();
fs.writeFileSync(out + "README.txt", "Generated by scripts/icons (Playwright + the design fonts).\n");
