// Light + dark for every app.
//
// The apps were each designed in one theme (my app dark, parent + notes light), with colours
// written inline. This script:
//   1. rewrites every inline hex colour in apps/src to a CSS variable (--c-rrggbb[aa]), once;
//   2. writes apps/src/lib/palette.css: the designed value for each, plus a "flipped" value used
//      when the app runs in its other theme. Neutrals mirror their lightness (backgrounds become
//      paper, text becomes ink, the hierarchy between them is kept); the brand orange and the
//      subject colours stay as they are; very dark or very light tints mirror too.
// Run: node scripts/theme-palette.mjs        (idempotent; CI runs it with --check)
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const SRC = path.join(root, "apps/src");
const OUT = path.join(SRC, "lib/palette.css");
const check = process.argv.includes("--check");

const files = [];
const walk = (d) => {
  for (const e of fs.readdirSync(d, { withFileTypes: true })) {
    const p = path.join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if ((/\.(tsx|ts|css)$/.test(e.name) && !e.name.endsWith(".test.ts")) && e.name !== "palette.css") files.push(p);
  }
};
walk(SRC);

const HEX = /(["'`(,\s:])#([0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?)(?![0-9a-fA-F])/g;
const used = new Set();
let changed = 0;
for (const f of files) {
  const s = fs.readFileSync(f, "utf8");
  const out = s.replace(HEX, (_m, pre, hex) => {
    used.add(hex.toLowerCase());
    return `${pre}var(--c-${hex.toLowerCase()})`;
  });
  for (const m of out.matchAll(/var\(--c-([0-9a-f]{6,8})\)/g)) used.add(m[1]);
  if (out !== s) {
    changed++;
    if (!check) fs.writeFileSync(f, out);
  }
}

// ---- colour maths (OKLab) ----
const srgb = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const unsrgb = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
function toLab([r, g, b]) {
  [r, g, b] = [r, g, b].map((v) => srgb(v / 255));
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s, 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s, 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s];
}
function fromLab([L, a, b]) {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  const rgb = [4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s, -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s, -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s];
  return rgb.map((v) => Math.round(Math.min(1, Math.max(0, unsrgb(Math.min(1, Math.max(0, v))))) * 255));
}
const hex2 = (n) => n.toString(16).padStart(2, "0");
function flip(hex) {
  const rgb = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16));
  const alpha = hex.slice(6);
  const [L, a, b] = toLab(rgb);
  const C = Math.hypot(a, b);
  // The brand orange and the subject colours keep their colour.
  if (C > 0.06 && L > 0.4 && L < 0.85) return hex;
  // Mirror lightness around the paper/ink pair (#0a0a0c ↔ #f4f3ef), keep the hue.
  const L2 = Math.min(0.975, Math.max(0.12, 1.1 - L));
  const k = C > 0.06 ? 1 : 0.6; // very dark/light tints keep more of their hue
  return fromLab([L2, a * k, b * k]).map(hex2).join("") + alpha;
}

const lines = [...used].sort();
const css =
  "/* generated by scripts/theme-palette.mjs — don't edit by hand */\n" +
  ":root {\n" + lines.map((h) => `  --c-${h}: #${h};`).join("\n") + "\n}\n" +
  "body.flip {\n" + lines.map((h) => `  --c-${h}: #${flip(h)};`).join("\n") + "\n}\n";

if (check) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (changed || cur !== css) {
    console.error(`theme palette out of date (${changed} files have raw colours). run: node scripts/theme-palette.mjs`);
    process.exit(1);
  }
  console.log(`theme palette ok (${lines.length} colours)`);
} else {
  fs.writeFileSync(OUT, css);
  console.log(`rewrote ${changed} files, ${lines.length} colours → ${path.relative(root, OUT)}`);
}
